### PR TITLE
ci(release): add linux/arm64 support

### PR DESCRIPTION
**Pull request by sdurrheimer**
Adding support for linux/arm64.

My use-case being that, on MacOS M1, docker builds are often virtualised as linux_arm64.
This also benefit regular linux on ARM users.

### CODE REVIEW

**Comment by sdurrheimer** [comment]
Hi @brad-jones, are you still supporting this repo?

**Comment by brad-jones** [comment]
Apologies @sdurrheimer, if I'm completely honest the use case I had for this tool is no longer a problem for me so no haven't really being paying any attention to this repo for some time now but it's a tool that I can still see has value.

Looks like the builds all passed, if you can fix up the commit message as per: https://github.com/brad-jones/hashdir/actions/runs/7260244288/job/20146158959?pr=72#step:4:567 I'll merge it.

**Comment by sdurrheimer** [comment]
Strange my commit doesn't have body lines, but I guess the job is taking the MR description as a commit.
I adapted the PR description to not have lines longer than 100 characters, but it will not trigger a re-build of the failed task automatically.

**Comment by brad-jones** [comment]
@sdurrheimer Bummer looks like the sigstore signing I was experimenting with is no longer working.
https://github.com/brad-jones/hashdir/actions/runs/7415183268/job/20177851259#step:6:782

I'll take a look when I can otherwise feel free to submit another PR if you want.

**Comment by sdurrheimer** [comment]
@brad-jones Maybe upgrading cosign would be enough:

```diff
diff --git i/.devcontainer/Dockerfile w/.devcontainer/Dockerfile
index f0e3570..cdd598d 100644
--- i/.devcontainer/Dockerfile
+++ w/.devcontainer/Dockerfile
@@ -54,8 +54,8 @@ ARG TARGET_SOCKET="/var/run/docker.sock"
 ARG ENTRYPOINT_LOGS="/tmp/entrypoint-logs"
 ARG NFPM_VERSION="2.11.3"
 ARG NFPM_SHA256="da82e726e83b39481e79b160262cf700750ca8b15a62f7bcb65d587f65f508fc"
-ARG COSIGN_VERSION="1.5.2"
-ARG COSIGN_SHA256="080c0ba10674d2909fb3b4b867b102aefa021959edf2696c8cc1ba08e824bccb"
+ARG COSIGN_VERSION="1.13.2"
+ARG COSIGN_SHA256="9b0f52abb2e6d79529f37646e524a35a409dc811d2cdec7ef5be2dc5130489c0"

 # UPSTREAM IMAGES
 # ------------------------------------------------------------------------------
diff --git i/.task/PackageTasks.yml w/.task/PackageTasks.yml
index a3684a7..6e147c1 100644
--- i/.task/PackageTasks.yml
+++ w/.task/PackageTasks.yml
@@ -71,7 +71,7 @@ tasks:
     cmds:
       - |
         for FILE in ./bin/*; do
-          cosign sign-blob \
+          cosign sign-blob --yes \
             --oidc-issuer https://token.actions.githubusercontent.com \
             --output-signature "${FILE}.sig" \
             --output-certificate "${FILE}.pem" \
```

**Pull request merged**
